<!DOCTYPE html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body class="min-vh-100 d-flex flex-column">
    <header class="flex-shrink-0">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
            <a href="/" class="navbar-brand">Анализатор страниц</a>
            <button class="navbar-toggler" ype="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
    <a class="nav-link" href="/">Главная</a>
</li>

                    <li class="nav-item">
    <a class="nav-link" href="/urls">Сайты</a>
</li>
                </ul>
            </div>
        </nav>
        </nav>
    </header>
    <?php if ($message): ?>
        <div class="alert alert-success" role="alert">
            <?= $message ?>
        </div>
    <?php endif; ?>

    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <h1>Сайт: <?= $url->getName() ?></h1>
            <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                    <tr>
                        <td>ID</td>
                        <td><?= $url->getId() ?></td>
                    </tr>
                    <tr>
                        <td>Имя</td>
                        <td><?= $url->getName() ?></td>
                    </tr>
                    <tr>
                        <td>Дата создания</td>
                        <td><?= $url->getCreationTime() ?></td>
                    </tr>
                </tbody>
            </table>
            </div>
            <h2 class="mt-5 md-3">Проверки</h2>
            <form class="mb-3" method="post" action="/urls/<?= $url->getId() ?>/checks">
                <input type="submit" class="btn btn-primary" value="Запустить проверку">
            </form>
            <table class="table table-bordered table-hover" data-test="checks">
                <tbody>
                    <tr>
                        <th>ID</th>
                        <th>Код ответа</th>
                        <th>h1</th>
                        <th>title</th>
                        <th>description</th>
                        <th>Дата создания</th>
                    </tr>
                </tbody>
            </table>
        </div>
    </main>
</body>
</html>